// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package xdp_sock

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadIpproto returns the embedded CollectionSpec for ipproto.
func loadIpproto() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_IpprotoBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ipproto: %w", err)
	}

	return spec, err
}

// loadIpprotoObjects loads ipproto and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ipprotoObjects
//	*ipprotoPrograms
//	*ipprotoMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadIpprotoObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadIpproto()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ipprotoSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ipprotoSpecs struct {
	ipprotoProgramSpecs
	ipprotoMapSpecs
	ipprotoVariableSpecs
}

// ipprotoProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ipprotoProgramSpecs struct {
	XdpSockProg *ebpf.ProgramSpec `ebpf:"xdp_sock_prog"`
}

// ipprotoMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ipprotoMapSpecs struct {
}

// ipprotoVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ipprotoVariableSpecs struct {
	PORT *ebpf.VariableSpec `ebpf:"PORT"`
}

// ipprotoObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadIpprotoObjects or ebpf.CollectionSpec.LoadAndAssign.
type ipprotoObjects struct {
	ipprotoPrograms
	ipprotoMaps
	ipprotoVariables
}

func (o *ipprotoObjects) Close() error {
	return _IpprotoClose(
		&o.ipprotoPrograms,
		&o.ipprotoMaps,
	)
}

// ipprotoMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadIpprotoObjects or ebpf.CollectionSpec.LoadAndAssign.
type ipprotoMaps struct {
}

func (m *ipprotoMaps) Close() error {
	return _IpprotoClose()
}

// ipprotoVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadIpprotoObjects or ebpf.CollectionSpec.LoadAndAssign.
type ipprotoVariables struct {
	PORT *ebpf.Variable `ebpf:"PORT"`
}

// ipprotoPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadIpprotoObjects or ebpf.CollectionSpec.LoadAndAssign.
type ipprotoPrograms struct {
	XdpSockProg *ebpf.Program `ebpf:"xdp_sock_prog"`
}

func (p *ipprotoPrograms) Close() error {
	return _IpprotoClose(
		p.XdpSockProg,
	)
}

func _IpprotoClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ipproto_bpfeb.o
var _IpprotoBytes []byte
